//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sehin_versión2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foto
    {
        public int Id { get; set; }
        public string ruta { get; set; }
        public string descripcion { get; set; }
        public int WorkOrderId { get; set; }
    
        public virtual Máquinas Máquinas { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
