//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sehin_versión2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenTrabajo
    {
        public int Id { get; set; }
        public string descripcion { get; set; }
        public string descripciondetallada { get; set; }
        public System.DateTime fechainicio { get; set; }
        public Nullable<System.DateTime> fechafin { get; set; }
        public string estado { get; set; }
        public bool finalizado { get; set; }
        public string prioridad { get; set; }
        public Nullable<bool> requierefirma { get; set; }
        public Nullable<System.DateTime> fechavencimiento { get; set; }
        public int diasprogramacion { get; set; }
        public System.DateTime fechafinprogracion { get; set; }
    }
}
