//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sehin_versión2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebFile
    {
        public int Id { get; set; }
        public byte[] Data { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string FileName { get; set; }
        public string FileExt { get; set; }
        public int FileLength { get; set; }
        public string ContentType { get; set; }
    }
}
