//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sehin_versión2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrder()
        {
            this.Foto = new HashSet<Foto>();
        }
    
        public int Id { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime fechavencimiento { get; set; }
        public Nullable<short> programacion { get; set; }
        public Nullable<short> prioridad { get; set; }
        public int TécnicosLegajo { get; set; }
        public Nullable<bool> finalizada { get; set; }
        public Nullable<System.DateTime> fechafinalizada { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Técnicos Técnicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foto> Foto { get; set; }
    }
}
